### ISSUE TITLE
What is the best size for batching up file operations?

### ISSUE THREAD

**Issue by bnlawrence** [cedadev/nlds#20]
As I understand it, the current NLDS version batches indexing tasks into chunks of `N` files (or the indexer does as it recurses, or both, I'm hazy on the details), and those batches become messages for "operation" in the system.  As it currently stands it has to be `N` files, as the choices of `V` GB is not available as the `os.stat` operation that would be needed to get file volumes is/was perceived as too expensive.  However, that stat will occur later with a different message, so I'm not sure that's a good argument for not doing it earlier in the workflow.  The advantage for doing it earlier in the workflow is that it could provide batch sizes which are optimal for tape residence by grouping up large numbers of small files or letting large files be handled separately.

It's worth thinking through when this should be done for most optimal results.

**Comment by nmassey001** [comment]
@jackleland Could you look into how much performance hit it would be to do a `os.stat` operation in the file scanner, please?

**Comment by jackleland** [comment]
UPDATE: The original point of this issue was to ask when the stat should take place, which was valid and has been addressed since #28. The benchmarking to find an optimum for this has yet to be carried out as it has not been a priority. 

The current design philosophy is that this batching up of file operations will also be used as the size of aggregations for the tape portion of the system #40. This may need to be split out in future if it turns out there are two competing optimum batch/aggregation sizes for the tape and the file statting, but for now will be left as a single configurable quantity (the `V` GB from Bryan's orignal comment).
